var shops = {"type": "FeatureCollection", "features": [
{"type": "Feature", "geometry": {"type": "Point", "coordinates": [13.101664, 51.121750]}, "properties": {"Name": "Autohaus Christian Ertl AG", "Straße": "Mastener Str. 1d", "Ort": "Döbeln", "Postleitzahl": "04720", "Telefon": "03431-66660", "Webseite": "www.ertl-gruppe.de", "E-Mail": "info@ertl-gruppe.de", "Info": "Autos & Werkstätten", "Rubrik": "Autos", "Stichworte":"Autohaus"}},
{"type": "Feature", "geometry": {"type": "Point", "coordinates": [13.031352, 51.065891]}, "properties": {"Name": "Ulrich Rudolph Wärmetechnik GmbH", "Straße": "Mortelstr. 27", "Ort": "Waldheim", "Postleitzahl": "04736", "Telefon": "034327-93660", "Webseite": "www.waermerudolph.de", "E-Mail": "info@waermerudolph.de", "Info": "Bauen & Renovieren", "Rubrik": "Bauen", "Stichworte":"Wärmetechnik, Heizung"}},
{"type": "Feature", "geometry": {"type": "Point", "coordinates": [13.123638, 51.122205]}, "properties": {"Name": "SD Immobilien und Hausverwaltungsdienst", "Straße": "Obermarkt 15", "Ort": "Döbeln", "Postleitzahl": "04720", "Telefon": "03431-571808", "Webseite": "www.rdm-regional.de", "E-Mail": "h-dietrich@rdm-regional.de", "Info": "Dienstleistungen", "Rubrik": "Dienstleistung", "Stichworte":"Immobilien, Hausverwaltung"}},
{"type": "Feature", "geometry": {"type": "Point", "coordinates": [13.221184, 51.223326]}, "properties": {"Name": "Vetter's Küche Aktiv GmbH", "Straße": "Riesaer Str. 8", "Ort": "Stauchitz", "Postleitzahl": "01594 ", "Telefon": "035268-8650", "Webseite": "www.kueche-aktiv-seerhausen.de", "E-Mail": "hinfo@kueche-aktiv-seerhausen.de", "Info": "Möbel & Wohnen", "Rubrik": "Wohnen", "Stichworte":"Immobilien, Hausverwaltung"}},
{"type": "Feature", "geometry": {"type": "Point", "coordinates": [13.151426, 51.204242]}, "properties": {"Name": "Vepo Polster Möbelhandelsgesellschaft mbH", "Straße": "Sachsenstr. 5", "Ort": "Ostrau", "Postleitzahl": "04749", "Telefon": "034324-22914", "Webseite": "Keine Angaben", "E-Mail": "vepopolster@yahoo.de", "Info": "Möbel & Wohnen", "Rubrik": "Wohnen", "Stichworte":"Polster"}},
{"type": "Feature", "geometry": {"type": "Point", "coordinates": [13.027991, 51.076303]}, "properties": {"Name": "Radio-Hellmuth", "Straße": "Niederstadt 18", "Ort": "Waldheim", "Postleitzahl": "04736", "Telefon": "034327-93614", "Webseite": "www.radio-hellmuth.de", "E-Mail": "info@radio-hellmuth.de", "Info": "Elektrik & Elektronik", "Rubrik": "Elektrik", "Stichworte":"Unterhaltungselektronik"}},
{"type": "Feature", "geometry": {"type": "Point", "coordinates": [13.117366, 51.120940]}, "properties": {"Name": "Steffen Greim", "Straße": "Rudolf-Breitscheid-Str. 1", "Ort": "Döbeln", "Postleitzahl": "04720", "Telefon": "03431-710238", "Webseite": "www.heizung-sanitaer-greim.de", "E-Mail": "info@heizung-sanitaer-greim.de", "Info": "Bauen & Renovieren", "Rubrik": "Bauen", "Stichworte":"Heizung, Sanitär"}},
{"type": "Feature", "geometry": {"type": "Point", "coordinates": [13.026430, 51.076476]}, "properties": {"Name": "Autohaus Häring e.K.", "Straße": "An der Zschopau 6", "Ort": "Waldheim", "Postleitzahl": "04736", "Telefon": "034327-92193", "Webseite": "www.autohaus-haering.de", "E-Mail": "info@autohaus-haering.de", "Info": "Autos & Werkstätten", "Rubrik": "Autos", "Stichworte":"Autohaus"}},
{"type": "Feature", "geometry": {"type": "Point", "coordinates": [13.121665, 51.122686]}, "properties": {"Name": "Studienkreis", "Straße": "Ritterstr. 5", "Ort": "Döbeln", "Postleitzahl": "04720", "Telefon": "03431-704152", "Webseite": "www.studienkreis.de", "E-Mail": "doebeln@studienkreis.de", "Info": "Bildung", "Rubrik": "Bildung", "Stichworte":"Nachhilfe, Schüler"}},
{"type": "Feature", "geometry": {"type": "Point", "coordinates": [13.098939, 51.137706]}, "properties": {"Name": "GW Gebäudereinigung u. Service GmbH", "Straße": "Zschepplitzer Str. 22", "Ort": "Döbeln", "Postleitzahl": "04720", "Telefon": "03431-612319", "Webseite": "Keine Angaben", "E-Mail": "Keine Angaben", "Rubrik": "Dienstleistung", "Info": "Dienstleistungen", "Stichworte":"Reinigung, Gebäudereinigung"}},
{"type": "Feature", "geometry": {"type": "Point", "coordinates": [13.109895, 51.178146]}, "properties": {"Name": "Renovierungsservice Herzog GmbH", "Straße": "Lindenstr. 9", "Ort": "Ostrau", "Postleitzahl": "04749", "Telefon": "034324-21249", "Webseite": "www.herzog.portas.de", "E-Mail": "info@herzog.portas.de", "Info": "Bauen & Renovieren ", "Rubrik": "Bauen", "Stichworte":"Renovieren"}},
{"type": "Feature", "geometry": {"type": "Point", "coordinates": [13.143174, 51.169955]}, "properties": {"Name": "tth Teppichmärkte", "Straße": "Am Wolfsgut 1", "Ort": "Zschaitz-Ottewig", "Postleitzahl": "04720", "Telefon": "034324-21893", "Webseite": "Keine Angaben", "E-Mail": "Keine Angaben", "Info": "Möbel & Wohnen", "Rubrik": "Wohnen", "Stichworte":"Teppich"}},
{"type": "Feature", "geometry": {"type": "Point", "coordinates": [13.123161, 51.121770]}, "properties": {"Name": "LSZ Döbeln Lern- und Sprachzentrum", "Straße": "Obermarkt 11", "Ort": "Döbeln", "Postleitzahl": "04720", "Telefon": "03431-706306", "Webseite": "www.lsz-doebeln.de", "E-Mail": "info@lsz-doebeln.de", "Info": "Bildung", "Rubrik": "Bildung", "Stichworte":"Sprachen, Lernen"}},

{"type": "Feature", "geometry": {"type": "Point", "coordinates": [13.003341, 51.075702]}, "properties": {"Name": "Automobilhandel Weirauch", "Straße": "Güterreihe 3a", "Ort": "Waldheim", "Postleitzahl": "04736", "Telefon": "034327-9530", "Webseite": "Keine Angaben", "E-Mail": "automobilhandel-weirauch@web.de", "Info": "Autos & Werkstätten", "Rubrik": "Autos", "Stichworte":"Autohandel"}},
{"type": "Feature", "geometry": {"type": "Point", "coordinates": [13.003341, 51.075702]}, "properties": {"Name": "Mahrenholz Fenster Holding GmbH", "Straße": "Mittelstr. 14", "Ort": "Ostrau", "Postleitzahl": "04749", "Telefon": "034324-5110", "Webseite": "https://mahrenholz.de/", "E-Mail": "ostrau@mahrenholz.de", "Info": "Bauen & Renovieren", "Rubrik": "Bauen", "Stichworte":"Fensterelementen, Haustüren"}},

{"type": "Feature", "geometry": {"type": "Point", "coordinates": [13.101597, 51.125726]}, "properties": {"Name": "Apotheke am Sternplatz", "Straße": "Weststr. 19", "Ort": "Döbeln", "Postleitzahl": "04720", "Telefon": "03431-610039", "Webseite": "www.apotheke-doebeln.de", "E-Mail": "info@apotheke-doebeln.de", "Rubrik": "Gesundheit", "Info": "Gesundheit", "Stichworte":"Apotheke, Medikamente"}},

{"type": "Feature", "geometry": {"type": "Point", "coordinates": [13.039463, 51.055033]}, "properties": {"Name": "RHG Raiffeisen Handelsgenossenschaft Mittelsachsen eG", "Straße": "Schönberg 28", "Ort": "Waldheim", "Postleitzahl": "04736", "Telefon": "034327-93884", "Webseite": "Keine Angaben", "E-Mail": "schulz.gartentechnik@t-online.de", "Info": "Bauen & Renovieren", "Rubrik": "Bauen", "Stichworte":"Raiffeisen-Markt, Baumarkt"}},
{"type": "Feature", "geometry": {"type": "Point", "coordinates": [13.153085, 51.119963]}, "properties": {"Name": "GRUMA Automobile GmbH", "Straße": "Daniel-Wilhelm-Beck-Str. 6", "Ort": "Döbeln", "Postleitzahl": "04720", "Telefon": "03431-57850", "Webseite": "www.mercedes-gruma.de", "E-Mail": "geschaeftsleitung@mercedes-gruma.de", "Info": "Autos & Werkstätten", "Rubrik": "Autos", "Stichworte":"Autohandel"}},
{"type": "Feature", "geometry": {"type": "Point", "coordinates": [12.982641, 51.057220]}, "properties": {"Name": "Auto-Gärtner", "Straße": "Reinsdorf 17", "Ort": "Waldheim", "Postleitzahl": "04736", "Telefon": "034327-54495", "Webseite": "www.auto-gaertner.de", "E-Mail": "post@auto-gaertner.de", "Info": "Autos & Werkstätten", "Rubrik": "Autos", "Stichworte":"Autohandel"}},

{"type": "Feature", "geometry": {"type": "Point", "coordinates": [13.118964, 50.974536]}, "properties": {"Name": "DRK KV Döbeln-Hainichen", "Straße": "Feldstr. 6", "Ort": "Hainichen", "Postleitzahl": "09661", "Telefon": "037207-6890", "Webseite": "www.dl-hc.drk.de", "E-Mail": "sekretariat@dl-hc.drk.de", "Rubrik": "Gesundheit", "Info": "Gesundheit", "Stichworte":"Rotes Kreuz, Erste Hilfe"}},
{"type": "Feature", "geometry": {"type": "Point", "coordinates": [13.123166, 51.120545]}, "properties": {"Name": "Manuela Luci & Matthias Clausner", "Straße": "Straße des Friedens 25", "Ort": "Döbeln", "Postleitzahl": "04720", "Telefon": "03431-703111", "Webseite": "Keine Angaben", "E-Mail": "Keine Angaben", "Rubrik": "Gesundheit", "Info": "Gesundheit", "Stichworte":"Gesundheit"}},
{"type": "Feature", "geometry": {"type": "Point", "coordinates": [13.143672, 51.121390]}, "properties": {"Name": "DEKRA  Automobil", "Straße": "Dresdner Str. 30b", "Ort": "Döbeln", "Postleitzahl": "04720", "Telefon": "03431-608100", "Webseite": "www.dekra.de/doebeln/portal.html", "E-Mail": "automobil@dekra.com", "Rubrik": "Autos", "Info": "Autos & Werkstätten", "Stichworte":"Autos, Prüfung"}},
{"type": "Feature", "geometry": {"type": "Point", "coordinates": [13.126021, 51.118989]}, "properties": {"Name": "Lerncenter Michaela Zimmermann", "Straße": "Gabelsbergerstr. 14", "Ort": "Döbeln", "Postleitzahl": "04720", "Telefon": "03431-571039", "Webseite": "Keine Angaben", "E-Mail": "lerncenter-doebeln@online.de", "Rubrik": "Bildung", "Info": "Bildung", "Stichworte":"Lernen, Nachhilfe"}},

{"type": "Feature", "geometry": {"type": "Point", "coordinates": [13.226409, 51.132590]}, "properties": {"Name": "Auto Grafe", "Straße": "Lüttewitz 23", "Ort": "Döbeln", "Postleitzahl": "04720", "Telefon": "034325-20363", "Webseite": "www.grafe-luettewitz.de", "E-Mail": "service@grafe-luettewitz.de", "Info": "Autos & Werkstätten", "Rubrik": "Autos", "Stichworte":"Autohandel"}},
{"type": "Feature", "geometry": {"type": "Point", "coordinates": [12.995613, 51.081693]}, "properties": {"Name": "Autohaus Mäke", "Straße": "Mendener Weg 1", "Ort": "Waldheim", "Postleitzahl": "04736", "Telefon": "034327-9600", "Webseite": "www.autohaus-maeke.de", "E-Mail": "waldheim@autohaus-maeke.de", "Info": "Autos & Werkstätten", "Rubrik": "Autos", "Stichworte":"Autohaus"}},
{"type": "Feature", "geometry": {"type": "Point", "coordinates": [12.931486, 51.160687]}, "properties": {"Name": "RHG Raiffeisen Handelsgenossenschaft Mittelsachsen eG", "Straße": "An der Muldenwiese 4b", "Ort": "Leisnig", "Postleitzahl": "04703", "Telefon": "034321-12956", "Webseite": "www.rhg-leisnig-oschatz.de", "E-Mail": "geschaeftsleitung@rhg-leisnig-oschatz.de", "Info": "Dienstleistungen", "Rubrik": "Dienstleistung", "Stichworte":"Baumarkt"}},
{"type": "Feature", "geometry": {"type": "Point", "coordinates": [13.183468, 51.069753]}, "properties": {"Name": "Gewe Wintergärten", "Straße": "Dr.-Otto-Nuschke-Str. 2a", "Ort": "Roßwein", "Postleitzahl": "04741", "Telefon": "034322-69720", "Webseite": "www.gewe.com", "E-Mail": "rosswein@gewe.com", "Info": "Bauen & Renovieren ", "Rubrik": "Bauen", "Stichworte":"Wintergärten"}},

{"type": "Feature", "geometry": {"type": "Point", "coordinates": [13.128702, 51.118822]}, "properties": {"Name": "Physiotherapie & Rehazentrum Döbeln", "Straße": "Thielestr. 17", "Ort": "Döbeln", "Postleitzahl": "04720", "Telefon": "03431-710806", "Webseite": "Keine Angaben", "E-Mail": "Keine Angaben", "Rubrik": "Gesundheit", "Info": "Gesundheit", "Stichworte":"Physiotherapie, Behandlung, Gesundheit"}},
{"type": "Feature", "geometry": {"type": "Point", "coordinates": [13.172381, 51.166763]}, "properties": {"Name": "SK-Gerüstbau UG", "Straße": "Am Doktorberg 1", "Ort": "Zschaitz-Ottewig", "Postleitzahl": "04720", "Telefon": "0152-04838782", "Webseite": "Keine Angaben", "E-Mail": "sk_geruestbau_ug@t-online.de", "Info": "Bauen & Renovieren ", "Rubrik": "Bauen", "Stichworte":"Gerüstbau"}},
{"type": "Feature", "geometry": {"type": "Point", "coordinates": [13.051603, 51.117683]}, "properties": {"Name": "Pflegeteam Sonnenschein", "Straße": "Mastener Weg 10", "Ort": "Döbeln", "Postleitzahl": "04720", "Telefon": "03431-7296854", "Webseite": "Keine Angaben", "E-Mail": "pflegeteam-sonnenschein@gmx.de", "Rubrik": "Gesundheit", "Info": "Gesundheit", "Stichworte":"Pflege, Gesundheit"}},
{"type": "Feature", "geometry": {"type": "Point", "coordinates": [12.973815, 51.099861]}, "properties": {"Name": "Hair Plus", "Straße": "Straße des Friedens 2A", "Ort": "Hartha", "Postleitzahl": "04746", "Telefon": "034328-41023", "Webseite": "Keine Angaben", "E-Mail": "hair-plus-hartha@web.de", "Info": "Dienstleistungen", "Rubrik": "Dienstleistung", "Stichworte":"Beauty, Frisör, Wellness"}},
{"type": "Feature", "geometry": {"type": "Point", "coordinates": [12.937457, 51.120026]}, "properties": {"Name": "Dachdeckermeister Ingolf Horn", "Straße": "Am Schanzenbach 105", "Ort": "Hartha", "Postleitzahl": "04746", "Telefon": "034328-66085", "Webseite": "Keine Angaben", "E-Mail": "dachdecker-horn@freenet.de", "Info": "Bauen & Renovieren ", "Rubrik": "Bauen", "Stichworte":"Dachdecker"}}]}